[workspace]
resolver = "2"
members = [
    "lib/srv/desktop/rdp/rdpclient",
    "web/packages/teleport/src/ironrdp"
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
homepage = "https://github.com/gravitational/teleport"
repository = "https://github.com/gravitational/teleport"
publish = false

[profile.dev]
debug = 1
lto = "off"

[profile.release]
debug = 1
codegen-units = 1

[workspace.dependencies]
# Note: To use a local IronRDP repository as a crate (for example, ironrdp-cliprdr), define the dependency as follows:
# ironrdp-cliprdr = { path = "../IronRDP/crates/ironrdp-cliprdr" }
ironrdp-cliprdr = { path = "../IronRDP/crates/ironrdp-cliprdr" }
ironrdp-connector = { path = "../IronRDP/crates/ironrdp-connector" }
ironrdp-displaycontrol = { path = "../IronRDP/crates/ironrdp-displaycontrol" }
ironrdp-dvc = { path = "../IronRDP/crates/ironrdp-dvc" }
ironrdp-graphics = { path = "../IronRDP/crates/ironrdp-graphics" }
ironrdp-pdu = { path = "../IronRDP/crates/ironrdp-pdu" }
ironrdp-rdpdr = { path = "../IronRDP/crates/ironrdp-rdpdr" }
ironrdp-rdpsnd = { path = "../IronRDP/crates/ironrdp-rdpsnd" }
ironrdp-session = { path = "../IronRDP/crates/ironrdp-session" }
ironrdp-svc = { path = "../IronRDP/crates/ironrdp-svc" }
ironrdp-tls = { path = "../IronRDP/crates/ironrdp-tls", features = ["rustls"] }
ironrdp-tokio = { path = "../IronRDP/crates/ironrdp-tokio" }
